import type { TablesInsert } from "@/types/database.types";

/**
 * Seed list of Four Mile Run / lower Potomac access points used to
 * bootstrap a fresh database in development. Coordinates are hand-
 * verified against OSM; lat/lng are stored as plain float8 (no PostGIS).
 *
 * Re-running the seed is idempotent via the unique `slug` column —
 * the seed route uses upsert on `slug`.
 */
export const fourMileRunSites: TablesInsert<"sites">[] = [
  {
    name: "Four Mile Run Kayak Launch (ADA)",
    slug: "four-mile-run-kayak-launch-ada",
    site_type: "kayak_launch",
    water_body_type: "freshwater",
    lat: 38.84044,
    lng: -77.05552,
    ada_accessible: true,
    description:
      "ADA-accessible kayak launch on Four Mile Run, just upstream of the Potomac confluence.",
    amenities: ["parking", "ada_ramp"],
    is_active: true,
  },
  {
    name: "Commonwealth Ave Ramp",
    slug: "commonwealth-ave-ramp",
    site_type: "kayak_launch",
    water_body_type: "freshwater",
    lat: 38.840322,
    lng: -77.055143,
    ada_accessible: false,
    description: "Informal kayak put-in near Commonwealth Avenue.",
    amenities: ["street_parking"],
    is_active: true,
  },
  {
    name: "Washington Sailing Marina",
    slug: "washington-sailing-marina",
    site_type: "marina",
    water_body_type: "tidal_brackish",
    lat: 38.833209,
    lng: -77.041684,
    ada_accessible: false,
    description: "Full-service marina on the tidal Potomac with sailboat and kayak rentals.",
    amenities: ["parking", "restrooms", "rentals", "food"],
    is_active: true,
  },
  {
    name: "Four Mile Run / Potomac Confluence",
    slug: "four-mile-run-potomac-confluence",
    site_type: "swim_area",
    water_body_type: "tidal_brackish",
    lat: 38.838,
    lng: -77.052,
    ada_accessible: false,
    description: "Tidal confluence where Four Mile Run meets the Potomac River.",
    amenities: [],
    is_active: true,
  },
  {
    name: "Gravelly Point Boat Ramp",
    slug: "gravelly-point-boat-ramp",
    site_type: "boat_ramp",
    water_body_type: "tidal_brackish",
    lat: 38.863958,
    lng: -77.04108,
    address: "12 Mt Vernon Trail, Arlington, VA 22202",
    is_active: false,
  },
  {
    name: "Anacostia Park Boat Ramp",
    slug: "anacostia-park-boat-ramp",
    site_type: "boat_ramp",
    water_body_type: "tidal_brackish",
    lat: 38.879743,
    lng: -76.970445,
    address: "1500 Anacostia Dr NE, Washington, DC 20020",
    is_active: false,
  },
  {
    name: "James Creek Marina",
    slug: "james-creek-marina",
    site_type: "marina",
    water_body_type: "tidal_brackish",
    lat: 38.86447,
    lng: -77.014802,
    address: "200 V St SW, Washington, DC 20024",
    is_active: false,
  },
  {
    name: "Belle Haven Marina",
    slug: "belle-haven-marina",
    site_type: "marina",
    water_body_type: "tidal_brackish",
    lat: 38.778453,
    lng: -77.049178,
    address: "1 Belle Haven Rd, Alexandria, VA 22307",
    is_active: false,
  },
  {
    name: "Pohick Bay Regional Boat Ramp",
    slug: "pohick-bay-boat-ramp",
    site_type: "boat_ramp",
    water_body_type: "tidal_brackish",
    lat: 38.671828,
    lng: -77.169097,
    address: "6501 Pohick Bay Dr, Lorton, VA 22079",
    is_active: false,
  },
  {
    name: "Pohick Bay Kayak Launch",
    slug: "pohick-bay-kayak-launch",
    site_type: "kayak_launch",
    water_body_type: "tidal_brackish",
    lat: 38.676756,
    lng: -77.168819,
    address: "Lorton, VA 22079",
    is_active: false,
  },
  {
    name: "Fountainhead Regional Park Boat Launch",
    slug: "fountainhead-boat-launch",
    site_type: "boat_ramp",
    water_body_type: "freshwater",
    lat: 38.720696,
    lng: -77.334197,
    address: "Fairfax Station, VA 22039",
    is_active: false,
  },
  {
    name: "Algonkian Regional Park Boat Ramp",
    slug: "algonkian-boat-ramp",
    site_type: "boat_ramp",
    water_body_type: "freshwater",
    lat: 39.062149,
    lng: -77.378397,
    address: "47001 Fairway Dr, Sterling, VA 20165",
    is_active: false,
  },
  {
    name: "River Bend Park Boat Ramp",
    slug: "river-bend-boat-ramp",
    site_type: "boat_ramp",
    water_body_type: "freshwater",
    lat: 39.018236,
    lng: -77.245606,
    address: "8700 Potomac Hills St, Great Falls, VA 22066",
    is_active: false,
  },
  {
    name: "Bladensburg Waterfront Park",
    slug: "bladensburg-waterfront",
    site_type: "kayak_launch",
    water_body_type: "freshwater",
    lat: 38.937796,
    lng: -76.939375,
    address: "4601 Annapolis Rd, Bladensburg, MD 20710",
    is_active: false,
  },
  {
    name: "Key Bridge Boathouse",
    slug: "key-bridge-boathouse",
    site_type: "kayak_launch",
    water_body_type: "tidal_brackish",
    lat: 38.90416,
    lng: -77.06969,
    address: "3500 Water St NW, Washington, DC 20007",
    is_active: false,
  },
  {
    name: "Thompson Boat Center",
    slug: "thompson-boat-center",
    site_type: "kayak_launch",
    water_body_type: "tidal_brackish",
    lat: 38.900297,
    lng: -77.058089,
    address: "2900 Virginia Ave NW, Washington, DC 20037",
    is_active: false,
  },
  {
    name: "Fletcher's Cove Boathouse",
    slug: "fletchers-cove",
    site_type: "kayak_launch",
    water_body_type: "freshwater",
    lat: 38.91918,
    lng: -77.101909,
    address: "4940 Canal Rd NW, Washington, DC 20016",
    is_active: false,
  },
];
