/**
 * Re-exports Supabase-generated Database types so the rest of the app
 * imports from a single, app-owned path (`@/types/database.types`)
 * instead of reaching into `src/integrations/supabase/types.ts` directly.
 *
 * The underlying types file is regenerated by Lovable Cloud whenever the
 * schema changes — never edit it by hand.
 */
export type {
  Database,
  Json,
  Tables,
  TablesInsert,
  TablesUpdate,
  Enums,
  CompositeTypes,
} from "@/integrations/supabase/types";

import type { Tables } from "@/integrations/supabase/types";

/** Row shape of `public.sites`. */
export type SiteRow = Tables<"sites">;
/** Row shape of `public.readings`. */
export type ReadingRow = Tables<"readings">;
/** Row shape of `public.user_profiles`. */
export type UserProfileRow = Tables<"user_profiles">;
/** Row shape of `public.favorites`. */
export type FavoriteRow = Tables<"favorites">;
/** Row shape of `public.alerts`. */
export type AlertRow = Tables<"alerts">;
/** Row shape of `public.rain_events`. */
export type RainEventRow = Tables<"rain_events">;
/** Row shape of `public.guest_alerts`. */
export type GuestAlertRow = Tables<"guest_alerts">;
