/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TidesRouteImport } from './routes/tides'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as ListRouteImport } from './routes/list'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RiversIndexRouteImport } from './routes/rivers.index'
import { Route as SitesSlugRouteImport } from './routes/sites/$slug'
import { Route as RiversGaugeIdRouteImport } from './routes/rivers.$gaugeId'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthUpdatePasswordRouteImport } from './routes/auth/update-password'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ApiSitesRouteImport } from './routes/api/sites'
import { Route as ApiSeedRouteImport } from './routes/api/seed'
import { Route as ApiRouteV2RouteImport } from './routes/api/route-v2'
import { Route as ApiGuestAlertRouteImport } from './routes/api/guest-alert'
import { Route as ApiExplainRouteImport } from './routes/api/explain'
import { Route as AuthenticatedFavoritesRouteImport } from './routes/_authenticated/favorites'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as ApiSitesChar91slugChar93RouteImport } from './routes/api/sites/[slug]'
import { Route as ApiPublicSendWeeklyFeedbackRouteImport } from './routes/api/public/send-weekly-feedback'
import { Route as ApiPublicIngestRouteImport } from './routes/api/public/ingest'
import { Route as ApiGuestAlertUnsubscribeRouteImport } from './routes/api/guest-alert/unsubscribe'
import { Route as ApiSitesChar91slugChar93ReadingsRouteImport } from './routes/api/sites/[slug]/readings'
import { Route as ApiGaugesBySiteChar91siteIdChar93RouteImport } from './routes/api/gauges/by-site/[siteId]'

const TidesRoute = TidesRouteImport.update({
  id: '/tides',
  path: '/tides',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ListRoute = ListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RiversIndexRoute = RiversIndexRouteImport.update({
  id: '/rivers/',
  path: '/rivers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesSlugRoute = SitesSlugRouteImport.update({
  id: '/sites/$slug',
  path: '/sites/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RiversGaugeIdRoute = RiversGaugeIdRouteImport.update({
  id: '/rivers/$gaugeId',
  path: '/rivers/$gaugeId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUpdatePasswordRoute = AuthUpdatePasswordRouteImport.update({
  id: '/auth/update-password',
  path: '/auth/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitesRoute = ApiSitesRouteImport.update({
  id: '/api/sites',
  path: '/api/sites',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeedRoute = ApiSeedRouteImport.update({
  id: '/api/seed',
  path: '/api/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRouteV2Route = ApiRouteV2RouteImport.update({
  id: '/api/route-v2',
  path: '/api/route-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGuestAlertRoute = ApiGuestAlertRouteImport.update({
  id: '/api/guest-alert',
  path: '/api/guest-alert',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExplainRoute = ApiExplainRouteImport.update({
  id: '/api/explain',
  path: '/api/explain',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFavoritesRoute = AuthenticatedFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiSitesChar91slugChar93Route =
  ApiSitesChar91slugChar93RouteImport.update({
    id: '/slug',
    path: '/slug',
    getParentRoute: () => ApiSitesRoute,
  } as any)
const ApiPublicSendWeeklyFeedbackRoute =
  ApiPublicSendWeeklyFeedbackRouteImport.update({
    id: '/api/public/send-weekly-feedback',
    path: '/api/public/send-weekly-feedback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIngestRoute = ApiPublicIngestRouteImport.update({
  id: '/api/public/ingest',
  path: '/api/public/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGuestAlertUnsubscribeRoute =
  ApiGuestAlertUnsubscribeRouteImport.update({
    id: '/unsubscribe',
    path: '/unsubscribe',
    getParentRoute: () => ApiGuestAlertRoute,
  } as any)
const ApiSitesChar91slugChar93ReadingsRoute =
  ApiSitesChar91slugChar93ReadingsRouteImport.update({
    id: '/readings',
    path: '/readings',
    getParentRoute: () => ApiSitesChar91slugChar93Route,
  } as any)
const ApiGaugesBySiteChar91siteIdChar93Route =
  ApiGaugesBySiteChar91siteIdChar93RouteImport.update({
    id: '/api/gauges/by-site/siteId',
    path: '/api/gauges/by-site/siteId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/list': typeof ListRoute
  '/plan': typeof PlanRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/tides': typeof TidesRoute
  '/account': typeof AuthenticatedAccountRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/api/explain': typeof ApiExplainRoute
  '/api/guest-alert': typeof ApiGuestAlertRouteWithChildren
  '/api/route-v2': typeof ApiRouteV2Route
  '/api/seed': typeof ApiSeedRoute
  '/api/sites': typeof ApiSitesRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/rivers/$gaugeId': typeof RiversGaugeIdRoute
  '/sites/$slug': typeof SitesSlugRoute
  '/rivers/': typeof RiversIndexRoute
  '/api/guest-alert/unsubscribe': typeof ApiGuestAlertUnsubscribeRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/send-weekly-feedback': typeof ApiPublicSendWeeklyFeedbackRoute
  '/api/sites/slug': typeof ApiSitesChar91slugChar93RouteWithChildren
  '/api/gauges/by-site/siteId': typeof ApiGaugesBySiteChar91siteIdChar93Route
  '/api/sites/slug/readings': typeof ApiSitesChar91slugChar93ReadingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/list': typeof ListRoute
  '/plan': typeof PlanRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/tides': typeof TidesRoute
  '/account': typeof AuthenticatedAccountRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/api/explain': typeof ApiExplainRoute
  '/api/guest-alert': typeof ApiGuestAlertRouteWithChildren
  '/api/route-v2': typeof ApiRouteV2Route
  '/api/seed': typeof ApiSeedRoute
  '/api/sites': typeof ApiSitesRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/rivers/$gaugeId': typeof RiversGaugeIdRoute
  '/sites/$slug': typeof SitesSlugRoute
  '/rivers': typeof RiversIndexRoute
  '/api/guest-alert/unsubscribe': typeof ApiGuestAlertUnsubscribeRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/send-weekly-feedback': typeof ApiPublicSendWeeklyFeedbackRoute
  '/api/sites/slug': typeof ApiSitesChar91slugChar93RouteWithChildren
  '/api/gauges/by-site/siteId': typeof ApiGaugesBySiteChar91siteIdChar93Route
  '/api/sites/slug/readings': typeof ApiSitesChar91slugChar93ReadingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/list': typeof ListRoute
  '/plan': typeof PlanRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/tides': typeof TidesRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/favorites': typeof AuthenticatedFavoritesRoute
  '/api/explain': typeof ApiExplainRoute
  '/api/guest-alert': typeof ApiGuestAlertRouteWithChildren
  '/api/route-v2': typeof ApiRouteV2Route
  '/api/seed': typeof ApiSeedRoute
  '/api/sites': typeof ApiSitesRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/rivers/$gaugeId': typeof RiversGaugeIdRoute
  '/sites/$slug': typeof SitesSlugRoute
  '/rivers/': typeof RiversIndexRoute
  '/api/guest-alert/unsubscribe': typeof ApiGuestAlertUnsubscribeRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/send-weekly-feedback': typeof ApiPublicSendWeeklyFeedbackRoute
  '/api/sites/slug': typeof ApiSitesChar91slugChar93RouteWithChildren
  '/api/gauges/by-site/siteId': typeof ApiGaugesBySiteChar91siteIdChar93Route
  '/api/sites/slug/readings': typeof ApiSitesChar91slugChar93ReadingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/list'
    | '/plan'
    | '/privacy'
    | '/terms'
    | '/tides'
    | '/account'
    | '/alerts'
    | '/favorites'
    | '/api/explain'
    | '/api/guest-alert'
    | '/api/route-v2'
    | '/api/seed'
    | '/api/sites'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/update-password'
    | '/auth/verify-email'
    | '/rivers/$gaugeId'
    | '/sites/$slug'
    | '/rivers/'
    | '/api/guest-alert/unsubscribe'
    | '/api/public/ingest'
    | '/api/public/send-weekly-feedback'
    | '/api/sites/slug'
    | '/api/gauges/by-site/siteId'
    | '/api/sites/slug/readings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/list'
    | '/plan'
    | '/privacy'
    | '/terms'
    | '/tides'
    | '/account'
    | '/alerts'
    | '/favorites'
    | '/api/explain'
    | '/api/guest-alert'
    | '/api/route-v2'
    | '/api/seed'
    | '/api/sites'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/update-password'
    | '/auth/verify-email'
    | '/rivers/$gaugeId'
    | '/sites/$slug'
    | '/rivers'
    | '/api/guest-alert/unsubscribe'
    | '/api/public/ingest'
    | '/api/public/send-weekly-feedback'
    | '/api/sites/slug'
    | '/api/gauges/by-site/siteId'
    | '/api/sites/slug/readings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/list'
    | '/plan'
    | '/privacy'
    | '/terms'
    | '/tides'
    | '/_authenticated/account'
    | '/_authenticated/alerts'
    | '/_authenticated/favorites'
    | '/api/explain'
    | '/api/guest-alert'
    | '/api/route-v2'
    | '/api/seed'
    | '/api/sites'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/update-password'
    | '/auth/verify-email'
    | '/rivers/$gaugeId'
    | '/sites/$slug'
    | '/rivers/'
    | '/api/guest-alert/unsubscribe'
    | '/api/public/ingest'
    | '/api/public/send-weekly-feedback'
    | '/api/sites/slug'
    | '/api/gauges/by-site/siteId'
    | '/api/sites/slug/readings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  ListRoute: typeof ListRoute
  PlanRoute: typeof PlanRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  TidesRoute: typeof TidesRoute
  ApiExplainRoute: typeof ApiExplainRoute
  ApiGuestAlertRoute: typeof ApiGuestAlertRouteWithChildren
  ApiRouteV2Route: typeof ApiRouteV2Route
  ApiSeedRoute: typeof ApiSeedRoute
  ApiSitesRoute: typeof ApiSitesRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthUpdatePasswordRoute: typeof AuthUpdatePasswordRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  RiversGaugeIdRoute: typeof RiversGaugeIdRoute
  SitesSlugRoute: typeof SitesSlugRoute
  RiversIndexRoute: typeof RiversIndexRoute
  ApiPublicIngestRoute: typeof ApiPublicIngestRoute
  ApiPublicSendWeeklyFeedbackRoute: typeof ApiPublicSendWeeklyFeedbackRoute
  ApiGaugesBySiteChar91siteIdChar93Route: typeof ApiGaugesBySiteChar91siteIdChar93Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tides': {
      id: '/tides'
      path: '/tides'
      fullPath: '/tides'
      preLoaderRoute: typeof TidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list': {
      id: '/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof ListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rivers/': {
      id: '/rivers/'
      path: '/rivers'
      fullPath: '/rivers/'
      preLoaderRoute: typeof RiversIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/$slug': {
      id: '/sites/$slug'
      path: '/sites/$slug'
      fullPath: '/sites/$slug'
      preLoaderRoute: typeof SitesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rivers/$gaugeId': {
      id: '/rivers/$gaugeId'
      path: '/rivers/$gaugeId'
      fullPath: '/rivers/$gaugeId'
      preLoaderRoute: typeof RiversGaugeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/update-password': {
      id: '/auth/update-password'
      path: '/auth/update-password'
      fullPath: '/auth/update-password'
      preLoaderRoute: typeof AuthUpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sites': {
      id: '/api/sites'
      path: '/api/sites'
      fullPath: '/api/sites'
      preLoaderRoute: typeof ApiSitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seed': {
      id: '/api/seed'
      path: '/api/seed'
      fullPath: '/api/seed'
      preLoaderRoute: typeof ApiSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/route-v2': {
      id: '/api/route-v2'
      path: '/api/route-v2'
      fullPath: '/api/route-v2'
      preLoaderRoute: typeof ApiRouteV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/guest-alert': {
      id: '/api/guest-alert'
      path: '/api/guest-alert'
      fullPath: '/api/guest-alert'
      preLoaderRoute: typeof ApiGuestAlertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/explain': {
      id: '/api/explain'
      path: '/api/explain'
      fullPath: '/api/explain'
      preLoaderRoute: typeof ApiExplainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/favorites': {
      id: '/_authenticated/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AuthenticatedFavoritesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/sites/slug': {
      id: '/api/sites/slug'
      path: '/slug'
      fullPath: '/api/sites/slug'
      preLoaderRoute: typeof ApiSitesChar91slugChar93RouteImport
      parentRoute: typeof ApiSitesRoute
    }
    '/api/public/send-weekly-feedback': {
      id: '/api/public/send-weekly-feedback'
      path: '/api/public/send-weekly-feedback'
      fullPath: '/api/public/send-weekly-feedback'
      preLoaderRoute: typeof ApiPublicSendWeeklyFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest': {
      id: '/api/public/ingest'
      path: '/api/public/ingest'
      fullPath: '/api/public/ingest'
      preLoaderRoute: typeof ApiPublicIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/guest-alert/unsubscribe': {
      id: '/api/guest-alert/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/api/guest-alert/unsubscribe'
      preLoaderRoute: typeof ApiGuestAlertUnsubscribeRouteImport
      parentRoute: typeof ApiGuestAlertRoute
    }
    '/api/sites/slug/readings': {
      id: '/api/sites/slug/readings'
      path: '/readings'
      fullPath: '/api/sites/slug/readings'
      preLoaderRoute: typeof ApiSitesChar91slugChar93ReadingsRouteImport
      parentRoute: typeof ApiSitesChar91slugChar93Route
    }
    '/api/gauges/by-site/siteId': {
      id: '/api/gauges/by-site/siteId'
      path: '/api/gauges/by-site/siteId'
      fullPath: '/api/gauges/by-site/siteId'
      preLoaderRoute: typeof ApiGaugesBySiteChar91siteIdChar93RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedFavoritesRoute: typeof AuthenticatedFavoritesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedFavoritesRoute: AuthenticatedFavoritesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiGuestAlertRouteChildren {
  ApiGuestAlertUnsubscribeRoute: typeof ApiGuestAlertUnsubscribeRoute
}

const ApiGuestAlertRouteChildren: ApiGuestAlertRouteChildren = {
  ApiGuestAlertUnsubscribeRoute: ApiGuestAlertUnsubscribeRoute,
}

const ApiGuestAlertRouteWithChildren = ApiGuestAlertRoute._addFileChildren(
  ApiGuestAlertRouteChildren,
)

interface ApiSitesChar91slugChar93RouteChildren {
  ApiSitesChar91slugChar93ReadingsRoute: typeof ApiSitesChar91slugChar93ReadingsRoute
}

const ApiSitesChar91slugChar93RouteChildren: ApiSitesChar91slugChar93RouteChildren =
  {
    ApiSitesChar91slugChar93ReadingsRoute:
      ApiSitesChar91slugChar93ReadingsRoute,
  }

const ApiSitesChar91slugChar93RouteWithChildren =
  ApiSitesChar91slugChar93Route._addFileChildren(
    ApiSitesChar91slugChar93RouteChildren,
  )

interface ApiSitesRouteChildren {
  ApiSitesChar91slugChar93Route: typeof ApiSitesChar91slugChar93RouteWithChildren
}

const ApiSitesRouteChildren: ApiSitesRouteChildren = {
  ApiSitesChar91slugChar93Route: ApiSitesChar91slugChar93RouteWithChildren,
}

const ApiSitesRouteWithChildren = ApiSitesRoute._addFileChildren(
  ApiSitesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  ListRoute: ListRoute,
  PlanRoute: PlanRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  TidesRoute: TidesRoute,
  ApiExplainRoute: ApiExplainRoute,
  ApiGuestAlertRoute: ApiGuestAlertRouteWithChildren,
  ApiRouteV2Route: ApiRouteV2Route,
  ApiSeedRoute: ApiSeedRoute,
  ApiSitesRoute: ApiSitesRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthUpdatePasswordRoute: AuthUpdatePasswordRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  RiversGaugeIdRoute: RiversGaugeIdRoute,
  SitesSlugRoute: SitesSlugRoute,
  RiversIndexRoute: RiversIndexRoute,
  ApiPublicIngestRoute: ApiPublicIngestRoute,
  ApiPublicSendWeeklyFeedbackRoute: ApiPublicSendWeeklyFeedbackRoute,
  ApiGaugesBySiteChar91siteIdChar93Route:
    ApiGaugesBySiteChar91siteIdChar93Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
